### ISSUE TITLE
Output volume on USB audio interface too low

### ISSUE THREAD

**Issue by eeeeeeek** [hassio-addons/addon-spotify-connect#179]
# Problem/Motivation

After updating from 0.11.0 to 0.12.1 on Home Assistant (core 2022.3.3 / OS 7.6) the output volume on my USB audio interface based on PCM2902 is much lower than before 

## Expected behavior

The output volume with version 0.12.1 is the same like with 0.11.0

## Actual behavior

The output volume with version 0.12.1 is approximately 25 % of the previous volume with version 0.11.0

## Steps to reproduce

Install version 0.12.1 and select an USB audio device as audio output 

## Proposed changes

Change the audio volume to the previous one

**Comment by eeeeeeek** [comment]
Issue still persistent after upgrade to latest release 0.12.2. Please reopen

**Comment by s-knibbs** [comment]
Same issue here, upgrading seems to have substantially reduced the output volume over hdmi.

**Comment by s-knibbs** [comment]
From what I've been able to gather, I believe that this may due to changes made to volume normalisation in librespot (see https://github.com/librespot-org/librespot/issues/855#issuecomment-928197054). It may be useful to expose some more of the [options](https://github.com/librespot-org/librespot/wiki/Options) in the add-on so that this can be controlled.

**Comment by spudje** [comment]
After upgrading to 0.12.2 this issue https://github.com/hassio-addons/addon-spotify-connect/issues/182 seems to have been resolved. But now I don't get any audio whatsoever. Tracks seem to play fine, also according to logs, which don't show any errors. However I don't have any audio on my Hass Blue (Odroid N2+ mini jack audio out). It's not "low volume", since when I crank up the volume to max, I still don't hear anything (apart from a bit of white noise)

Squeezelite addon works just fine.

**Comment by pablinho1023** [comment]
I am having the same problem. The configuration shows my USB speaker and the log shows that a song is being played but there's no audio coming out. If I run ha audio info on the terminal, I see my speaker under output: -card: 1, mute: false, volume: 0.5411.

Is there a way to fix it?

**Comment by JxxIT** [comment]
#190 Looks the same, is this related?

**Comment by panchomira** [comment]
Hello everyone, I had the same issue and I fixed it using an external usb audio device attached to an x86 machine running HAOS. 

First, with no headphone jack inserted, audio was coming out of the built-in speakers of the laptop, but when I connected the headphones no audio would come out. Something interesting happened tho, audio was coming out of the mic imput. Then I tried the VLC add-on to check if it was and Add-on issue or a system issue. No luck with VLC, which makes me thing its a system issue, the x86 machina has a Realtek card. I plugged an external card, selected it in the config, and works GREAT. Thank you developers!

**Comment by spudje** [comment]
That's not a solution for people like me who run Home Assistant on something like Odroid. I hope @frenck will come with a fix or at least some feedback regarding the issue soon.

**Comment by gerliczky** [comment]
I am not sure I have the same problem, but if I play a song using spotify connect on Home assistant it is really quiet. If I play for example a radio stream on mopidy it's volume is normal. Is the problem on the addon side, or somehow on Spotify side? Spotify sounds normal on other devices.

**Comment by pablinho1023** [comment]
I don't think any support is given. I asked in the HA discord and was ignored while all the other questions were addressed.

**Comment by panchomira** [comment]
It would be nice to take a look at the code
