### ISSUE TITLE
Using spotify-connect with multiple accounts

### ISSUE THREAD

**Issue by Johnadc2** [hassio-addons/addon-spotify-connect#5]
# Problem/Motivation

Hi there. Thank you for a great add-on! We are now enjoying Spotify in multiple rooms. I'm wondering wether it would be somehow possible to change this add-on so it can be controlled by more than one premium account. We all have our own Spotify premium (family) account at home, but only the one who has entered his/her username and pw in the spotify-connect addon is able to connect to it. The only option at the moment is to all use the same Spotify account. 

Regards,
John

**Comment by frenck** [comment]
This is not a thing I can add.
An addon wraps existing software, in this case, SpotifyD.
Unfortunately, it does not support that. I know it is requested a lot and hopefully, the upstream project is going to implement it. If they do, the add-on will receive that update/feature as well of course.

Closing this issue, since this is not something I can solve.
